---
name: Publish Website

on:
  push:
    branches:
      - "!*"
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@2.0.0
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          BRANCH: gh-pages
          BUILD_SCRIPT: npm install && npm run build
          COMMIT_EMAIL: robots@octopusthink.com
          COMMIT_NAME: Octopus Think Robot
          CNAME: octopusthink.com
          FOLDER: public
