---
name: Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/cache@v1
        name: Cache npm modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v1
        name: Cache Gatsby build
        with:
          path: ./.cache
          key: ${{ runner.os }}-node-gatsby-cache-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('static/**/**') }}
          restore-keys: |
            ${{ runner.os }}-node-gatsby-cache-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('static/**/**') }}
      - uses: actions/cache@v1
        name: Cache Gatsby public folder
        with:
          path: ./public
          key: ${{ runner.os }}-node-gatsby-public-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('static/**/**') }}
          restore-keys: |
            ${{ runner.os }}-node-gatsby-public-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('static/**/**') }}
      - name: Install dependencies
        run: npm install
      - name: Build site
        run: npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/cache@v1
        name: Cache npm modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Lint JS
        run: npm run lint
